export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { emailText } = req.body;
  if (!emailText) {
    return res.status(400).json({ error: 'Missing emailText' });
  }

  const token = process.env.VITE_HUGGINGFACE_TOKEN;
  const API_URL = 'https://api-inference.huggingface.co/models/google/flan-t5-base';

  try {
    const hfResponse = await fetch(API_URL, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        inputs: `Generate a short, polite reply to this email:\n\n${emailText}`,
      }),
    });

    const hfData = await hfResponse.json();

    if (hfData.error) {
      return res.status(500).json({ error: `Model error: ${hfData.error}` });
    }

    const reply = Array.isArray(hfData)
      ? hfData[0]?.generated_text
      : hfData?.generated_text;

    if (!reply || reply.trim() === '') {
      return res.status(500).json({ error: 'No reply generated by model.' });
    }

    return res.status(200).json({ reply: reply.trim() });
  } catch (error) {
    return res.status(500).json({ error: error.message || 'Internal server error' });
  }
}
